version: "3.8"
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  
  web:
    build: .
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  runner:
    build: .
    volumes:
      - .:/app
    command: /bin/zsh
    ports:
      - '3000:3000'